# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainWindowXpHLMM.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDialog,
    QLabel, QListView, QPushButton, QSizePolicy,
    QWidget)

class Ui_AutoTennis(object):
    def setupUi(self, AutoTennis):
        if not AutoTennis.objectName():
            AutoTennis.setObjectName(u"AutoTennis")
        AutoTennis.resize(688, 725)
        self.actionButton = QPushButton(AutoTennis)
        self.actionButton.setObjectName(u"actionButton")
        self.actionButton.setGeometry(QRect(550, 670, 100, 32))
        self.label = QLabel(AutoTennis)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(40, 240, 151, 20))
        self.label_3 = QLabel(AutoTennis)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(40, 80, 58, 16))
        self.fail_list_view = QListView(AutoTennis)
        self.fail_list_view.setObjectName(u"fail_list_view")
        self.fail_list_view.setGeometry(QRect(40, 270, 611, 171))
        self.mon_chk_box = QCheckBox(AutoTennis)
        self.mon_chk_box.setObjectName(u"mon_chk_box")
        self.mon_chk_box.setGeometry(QRect(40, 110, 51, 20))
        self.tue_chk_box = QCheckBox(AutoTennis)
        self.tue_chk_box.setObjectName(u"tue_chk_box")
        self.tue_chk_box.setGeometry(QRect(80, 110, 51, 20))
        self.wed_chk_box = QCheckBox(AutoTennis)
        self.wed_chk_box.setObjectName(u"wed_chk_box")
        self.wed_chk_box.setGeometry(QRect(120, 110, 41, 20))
        self.thu_chk_box = QCheckBox(AutoTennis)
        self.thu_chk_box.setObjectName(u"thu_chk_box")
        self.thu_chk_box.setGeometry(QRect(160, 110, 41, 20))
        self.fri_chk_box = QCheckBox(AutoTennis)
        self.fri_chk_box.setObjectName(u"fri_chk_box")
        self.fri_chk_box.setGeometry(QRect(200, 110, 41, 20))
        self.sat_chk_box = QCheckBox(AutoTennis)
        self.sat_chk_box.setObjectName(u"sat_chk_box")
        self.sat_chk_box.setGeometry(QRect(240, 110, 41, 20))
        self.sun_chk_box = QCheckBox(AutoTennis)
        self.sun_chk_box.setObjectName(u"sun_chk_box")
        self.sun_chk_box.setGeometry(QRect(280, 110, 51, 20))
        self.time_combo_box = QComboBox(AutoTennis)
        self.time_combo_box.setObjectName(u"time_combo_box")
        self.time_combo_box.setGeometry(QRect(40, 180, 181, 31))
        self.label_4 = QLabel(AutoTennis)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(40, 160, 58, 16))
        self.pass_list_view = QListView(AutoTennis)
        self.pass_list_view.setObjectName(u"pass_list_view")
        self.pass_list_view.setGeometry(QRect(40, 490, 611, 161))
        self.label_2 = QLabel(AutoTennis)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(40, 460, 151, 20))
        self.jungu1_chk_box = QCheckBox(AutoTennis)
        self.jungu1_chk_box.setObjectName(u"jungu1_chk_box")
        self.jungu1_chk_box.setGeometry(QRect(340, 50, 51, 21))
        self.label_5 = QLabel(AutoTennis)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(40, 20, 71, 16))
        self.jungu2_chk_box = QCheckBox(AutoTennis)
        self.jungu2_chk_box.setObjectName(u"jungu2_chk_box")
        self.jungu2_chk_box.setGeometry(QRect(400, 50, 51, 20))
        self.jungu3_chk_box = QCheckBox(AutoTennis)
        self.jungu3_chk_box.setObjectName(u"jungu3_chk_box")
        self.jungu3_chk_box.setGeometry(QRect(460, 50, 51, 20))
        self.jungu4_chk_box = QCheckBox(AutoTennis)
        self.jungu4_chk_box.setObjectName(u"jungu4_chk_box")
        self.jungu4_chk_box.setGeometry(QRect(520, 50, 51, 20))
        self.sinea1_chk_box = QCheckBox(AutoTennis)
        self.sinea1_chk_box.setObjectName(u"sinea1_chk_box")
        self.sinea1_chk_box.setGeometry(QRect(40, 50, 51, 21))
        self.sinea2_chk_box = QCheckBox(AutoTennis)
        self.sinea2_chk_box.setObjectName(u"sinea2_chk_box")
        self.sinea2_chk_box.setGeometry(QRect(100, 50, 51, 21))
        self.yaw3_chk_box = QCheckBox(AutoTennis)
        self.yaw3_chk_box.setObjectName(u"yaw3_chk_box")
        self.yaw3_chk_box.setGeometry(QRect(160, 50, 51, 21))
        self.yaw4_chk_box = QCheckBox(AutoTennis)
        self.yaw4_chk_box.setObjectName(u"yaw4_chk_box")
        self.yaw4_chk_box.setGeometry(QRect(220, 50, 51, 21))
        self.yaw7_chk_box = QCheckBox(AutoTennis)
        self.yaw7_chk_box.setObjectName(u"yaw7_chk_box")
        self.yaw7_chk_box.setGeometry(QRect(280, 50, 51, 21))
        self.next_month_chk_box = QCheckBox(AutoTennis)
        self.next_month_chk_box.setObjectName(u"next_month_chk_box")
        self.next_month_chk_box.setGeometry(QRect(120, 10, 111, 31))
        self.time2_combo_box = QComboBox(AutoTennis)
        self.time2_combo_box.setObjectName(u"time2_combo_box")
        self.time2_combo_box.setGeometry(QRect(250, 180, 181, 31))
        self.label_6 = QLabel(AutoTennis)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(250, 160, 58, 16))
        self.time3_combo_box = QComboBox(AutoTennis)
        self.time3_combo_box.setObjectName(u"time3_combo_box")
        self.time3_combo_box.setGeometry(QRect(460, 180, 181, 31))
        self.label_7 = QLabel(AutoTennis)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(460, 160, 58, 16))

        self.retranslateUi(AutoTennis)

        QMetaObject.connectSlotsByName(AutoTennis)
    # setupUi

    def retranslateUi(self, AutoTennis):
        AutoTennis.setWindowTitle(QCoreApplication.translate("AutoTennis", u"Dialog", None))
        self.actionButton.setText(QCoreApplication.translate("AutoTennis", u"\uc790\ub3d9\uc608\uc57d", None))
        self.label.setText(QCoreApplication.translate("AutoTennis", u"\uc2e4\ud328\ud55c \ub0a0\uc9dc", None))
        self.label_3.setText(QCoreApplication.translate("AutoTennis", u"\uc694\uc77c", None))
        self.mon_chk_box.setText(QCoreApplication.translate("AutoTennis", u"\uc6d4", None))
        self.tue_chk_box.setText(QCoreApplication.translate("AutoTennis", u"\ud654", None))
        self.wed_chk_box.setText(QCoreApplication.translate("AutoTennis", u"\uc218", None))
        self.thu_chk_box.setText(QCoreApplication.translate("AutoTennis", u"\ubaa9", None))
        self.fri_chk_box.setText(QCoreApplication.translate("AutoTennis", u"\uae08", None))
        self.sat_chk_box.setText(QCoreApplication.translate("AutoTennis", u"\ud1a0", None))
        self.sun_chk_box.setText(QCoreApplication.translate("AutoTennis", u"\uc77c", None))
        self.label_4.setText(QCoreApplication.translate("AutoTennis", u"\uc2dc\uac04\ub3001", None))
        self.label_2.setText(QCoreApplication.translate("AutoTennis", u"\uc131\uacf5\ud55c \ub0a0\uc9dc", None))
        self.jungu1_chk_box.setText(QCoreApplication.translate("AutoTennis", u"\uc815\uad6c1", None))
        self.label_5.setText(QCoreApplication.translate("AutoTennis", u"\ud14c\ub2c8\uc2a4 \uc7a5\uc18c", None))
        self.jungu2_chk_box.setText(QCoreApplication.translate("AutoTennis", u"\uc815\uad6c2", None))
        self.jungu3_chk_box.setText(QCoreApplication.translate("AutoTennis", u"\uc815\uad6c3", None))
        self.jungu4_chk_box.setText(QCoreApplication.translate("AutoTennis", u"\uc815\uad6c4", None))
        self.sinea1_chk_box.setText(QCoreApplication.translate("AutoTennis", u"\uc2e4\ub0b41", None))
        self.sinea2_chk_box.setText(QCoreApplication.translate("AutoTennis", u"\uc2e4\ub0b42", None))
        self.yaw3_chk_box.setText(QCoreApplication.translate("AutoTennis", u"\uc57c\uc6783", None))
        self.yaw4_chk_box.setText(QCoreApplication.translate("AutoTennis", u"\uc57c\uc6784", None))
        self.yaw7_chk_box.setText(QCoreApplication.translate("AutoTennis", u"\uc57c\uc6787", None))
        self.next_month_chk_box.setText(QCoreApplication.translate("AutoTennis", u"\ub2e4\uc74c\ub2ec \uc608\uc57d\ud558\uae30", None))
        self.label_6.setText(QCoreApplication.translate("AutoTennis", u"\uc2dc\uac04\ub3002", None))
        self.label_7.setText(QCoreApplication.translate("AutoTennis", u"\uc2dc\uac04\ub3003", None))
    # retranslateUi

